apiVersion: apimanagement.azure.com/v1api20220801
kind: Backend
metadata:
  name: petstore
  namespace: default
spec:
  description: Petstore
  protocol: http
  url: https://petstore.swagger.io/v2
  tls:
    validateCertificateChain: true
    validateCertificateName: true
  owner:
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}/providers/Microsoft.ApiManagement/service/${APIM_NAME}
