apiVersion: apimanagement.azure.com/v1api20220801
kind: Policy
metadata:
  name: sampleapimpolicy
  namespace: default
spec:
  value: <policies>
          <inbound />
          <backend>
            <forward-request />
          </backend>
          <outbound />
        </policies>
  owner:
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}/providers/Microsoft.ApiManagement/service/${APIM_NAME}
