apiVersion: apimanagement.azure.com/v1api20220801
kind: Product
metadata:
  name: sampleapimproduct
  namespace: default
spec:
  displayName: Customer 1
  description: A product for customer 1
  subscriptionRequired: true
  owner:
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}/providers/Microsoft.ApiManagement/service/${APIM_NAME}
