apiVersion: apimanagement.azure.com/v1api20220801
kind: Subscription
metadata:
  name: sampleapimsubscription
  namespace: default
spec:
  displayName: Sample subscription
  scope: /apis
  owner:
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}/providers/Microsoft.ApiManagement/service/${APIM_NAME}
